export const TREBLE_NOTES = [
  { name: 'G', key: 'g/3', difficulty: 'advanced' },
  { name: 'G#', key: 'g#/3', difficulty: 'advanced', alternatives: ['AB', 'GISS', 'ASS'] },
  { name: 'A', key: 'a/3', difficulty: 'advanced' },
  { name: 'A#', key: 'a#/3', difficulty: 'advanced', alternatives: ['BB', 'AISS', 'BESS'] },
  { name: 'B', key: 'b/3', difficulty: 'advanced', alternatives: ['H'] },
  { name: 'C', key: 'c/4', difficulty: 'beginner' },
  { name: 'C#', key: 'c#/4', difficulty: 'intermediate', alternatives: ['DB', 'CISS', 'DESS'] },
  { name: 'D', key: 'd/4', difficulty: 'beginner' },
  { name: 'D#', key: 'd#/4', difficulty: 'intermediate', alternatives: ['EB', 'DISS', 'ESS'] },
  { name: 'E', key: 'e/4', difficulty: 'beginner' },
  { name: 'F', key: 'f/4', difficulty: 'beginner' },
  { name: 'F#', key: 'f#/4', difficulty: 'intermediate', alternatives: ['GB', 'FISS', 'GESS'] },
  { name: 'G', key: 'g/4', difficulty: 'beginner' },
  { name: 'G#', key: 'g#/4', difficulty: 'intermediate', alternatives: ['AB', 'GISS', 'ASS'] },
  { name: 'A', key: 'a/4', difficulty: 'beginner' },
  { name: 'A#', key: 'a#/4', difficulty: 'intermediate', alternatives: ['BB', 'AISS', 'BESS'] },
  { name: 'B', key: 'b/4', difficulty: 'beginner', alternatives: ['H'] },
  { name: 'C', key: 'c/5', difficulty: 'beginner' },
  { name: 'D', key: 'd/5', difficulty: 'advanced' },
  { name: 'D#', key: 'd#/5', difficulty: 'advanced', alternatives: ['EB', 'DISS', 'ESS'] },
  { name: 'E', key: 'e/5', difficulty: 'advanced' },
];

export const BASS_NOTES = [
  { name: 'C', key: 'c/2', difficulty: 'advanced' },
  { name: 'C#', key: 'c#/2', difficulty: 'advanced', alternatives: ['DB', 'CISS', 'DESS'] },
  { name: 'D', key: 'd/2', difficulty: 'advanced' },
  { name: 'D#', key: 'd#/2', difficulty: 'advanced', alternatives: ['EB', 'DISS', 'ESS'] },
  { name: 'E', key: 'e/2', difficulty: 'advanced' },
  { name: 'F', key: 'f/2', difficulty: 'beginner' },
  { name: 'F#', key: 'f#/2', difficulty: 'intermediate', alternatives: ['GB', 'FISS', 'GESS'] },
  { name: 'G', key: 'g/2', difficulty: 'beginner' },
  { name: 'G#', key: 'g#/2', difficulty: 'intermediate', alternatives: ['AB', 'GISS', 'ASS'] },
  { name: 'A', key: 'a/2', difficulty: 'beginner' },
  { name: 'A#', key: 'a#/2', difficulty: 'intermediate', alternatives: ['BB', 'AISS', 'BESS'] },
  { name: 'B', key: 'b/2', difficulty: 'beginner', alternatives: ['H'] },
  { name: 'C', key: 'c/3', difficulty: 'beginner' },
  { name: 'C#', key: 'c#/3', difficulty: 'intermediate', alternatives: ['DB', 'CISS', 'DESS'] },
  { name: 'D', key: 'd/3', difficulty: 'beginner' },
  { name: 'D#', key: 'd#/3', difficulty: 'intermediate', alternatives: ['EB', 'DISS', 'ESS'] },
  { name: 'E', key: 'e/3', difficulty: 'beginner' },
  { name: 'F', key: 'f/3', difficulty: 'beginner' },
  { name: 'F#', key: 'f#/3', difficulty: 'intermediate', alternatives: ['GB', 'FISS', 'GESS'] },
  { name: 'G', key: 'g/3', difficulty: 'beginner' },
  { name: 'G#', key: 'g#/3', difficulty: 'intermediate', alternatives: ['AB', 'GISS', 'ASS'] },
  { name: 'A', key: 'a/3', difficulty: 'beginner' },
  { name: 'A#', key: 'a#/3', difficulty: 'intermediate', alternatives: ['BB', 'AISS', 'BESS'] },
  { name: 'B', key: 'b/3', difficulty: 'beginner', alternatives: ['H'] },
  { name: 'C', key: 'c/4', difficulty: 'beginner' },
  { name: 'D', key: 'd/4', difficulty: 'advanced' },
  { name: 'D#', key: 'd#/4', difficulty: 'advanced', alternatives: ['EB', 'DISS', 'ESS'] },
  { name: 'E', key: 'e/4', difficulty: 'advanced' },
];
