export const TREBLE_NOTES = [
  { name: 'C', key: 'c/4' },
  { name: 'C#', key: 'c#/4', alternatives: ['DB', 'CISS', 'DESS'] },
  { name: 'D', key: 'd/4' },
  { name: 'D#', key: 'd#/4', alternatives: ['EB', 'DISS', 'ESS'] },
  { name: 'E', key: 'e/4' },
  { name: 'F', key: 'f/4' },
  { name: 'F#', key: 'f#/4', alternatives: ['GB', 'FISS', 'GESS'] },
  { name: 'G', key: 'g/4' },
  { name: 'G#', key: 'g#/4', alternatives: ['AB', 'GISS', 'ASS'] },
  { name: 'A', key: 'a/4' },
  { name: 'A#', key: 'a#/4', alternatives: ['BB', 'AISS', 'BESS'] },
  { name: 'B', key: 'b/4', alternatives: ['H'] },
  { name: 'C', key: 'c/5' },
];

export const BASS_NOTES = [
  { name: 'F', key: 'f/2' },
  { name: 'F#', key: 'f#/2', alternatives: ['GB', 'FISS', 'GESS'] },
  { name: 'G', key: 'g/2' },
  { name: 'G#', key: 'g#/2', alternatives: ['AB', 'GISS', 'ASS'] },
  { name: 'A', key: 'a/2' },
  { name: 'A#', key: 'a#/2', alternatives: ['BB', 'AISS', 'BESS'] },
  { name: 'B', key: 'b/2', alternatives: ['H'] },
  { name: 'C', key: 'c/3' },
  { name: 'C#', key: 'c#/3', alternatives: ['DB', 'CISS', 'DESS'] },
  { name: 'D', key: 'd/3' },
  { name: 'D#', key: 'd#/3', alternatives: ['EB', 'DISS', 'ESS'] },
  { name: 'E', key: 'e/3' },
  { name: 'F', key: 'f/3' },
  { name: 'F#', key: 'f#/3', alternatives: ['GB', 'FISS', 'GESS'] },
  { name: 'G', key: 'g/3' },
  { name: 'G#', key: 'g#/3', alternatives: ['AB', 'GISS', 'ASS'] },
  { name: 'A', key: 'a/3' },
  { name: 'A#', key: 'a#/3', alternatives: ['BB', 'AISS', 'BESS'] },
  { name: 'B', key: 'b/3', alternatives: ['H'] },
  { name: 'C', key: 'c/4' },
];
